apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/cspeed-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: todos
            - name: DB_PASSWORD
              value: cspeed
            - name: DB_USER
              value: cspeed
          image: muhammedriaz/cspeed-backend:latest
          name: backend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
